# fly.toml app configuration file generated for little-bo-peep-leptos-dev on 2023-11-10T12:24:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "little-bo-peep-leptos-dev"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
