name: Fly Deploy
on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "ENV=production" > .env
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "ENV=development" > .env
          else
            echo "Unknown branch" > .env
          fi

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            flyctl deploy --remote-only --no-cache --app little-bo-peep
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            flyctl deploy --remote-only --no-cache --app little-bo-peep-develop
          else
            echo "Unknown branch, deployment skipped"
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
